copy /y "%XEngine_Library%\x86\XEngine_BaseLib\XEngine_BaseLib.dll" "./"
copy /y "%XEngine_Library%\x86\XEngine_AVCoder\XEngine_VideoCoder.dll" "./"
copy /y "%XEngine_Library%\x86\XEngine_AVCoder\XEngine_AudioCoder.dll" "./"
copy /y "%XEngine_Library%\x86\XEngine_AVCoder\XEngine_AVCollect.dll" "./"
copy /y "%XEngine_Library%\x86\XEngine_AVCoder\XEngine_AVHelp.dll" "./"
copy /y "%XEngine_Library%\x86\XEngine_AVCoder\XEngine_AVPacket.dll" "./"

copy /y "%XEngine_Library%\x86\XEngine_LibEx\AVCodec\avcodec-58.dll" "./"
copy /y "%XEngine_Library%\x86\XEngine_LibEx\AVCodec\avdevice-58.dll" "./"
copy /y "%XEngine_Library%\x86\XEngine_LibEx\AVCodec\avfilter-7.dll" "./"
copy /y "%XEngine_Library%\x86\XEngine_LibEx\AVCodec\avformat-58.dll" "./"
copy /y "%XEngine_Library%\x86\XEngine_LibEx\AVCodec\avutil-56.dll" "./"
copy /y "%XEngine_Library%\x86\XEngine_LibEx\AVCodec\postproc-55.dll" "./"
copy /y "%XEngine_Library%\x86\XEngine_LibEx\AVCodec\swresample-3.dll" "./"
copy /y "%XEngine_Library%\x86\XEngine_LibEx\AVCodec\swscale-5.dll" "./"