copy /y "..\libxengine\XEngine_Windows\x86\XEngine_BaseLib\XEngine_BaseLib.dll" ".\XEngine_Bin\XEngine_BaseLib.dll"
copy /y "..\libxengine\XEngine_Windows\x86\XEngine_AVCoder\XEngine_VideoCoder.dll" ".\XEngine_Bin\XEngine_VideoCoder.dll"
copy /y "..\libxengine\XEngine_Windows\x86\XEngine_AVCoder\XEngine_AudioCoder.dll" ".\XEngine_Bin\XEngine_AudioCoder.dll"
copy /y "..\libxengine\XEngine_Windows\x86\XEngine_AVCoder\XEngine_AVCollect.dll" ".\XEngine_Bin\XEngine_AVCollect.dll"
copy /y "..\libxengine\XEngine_Windows\x86\XEngine_AVCoder\XEngine_AVHelp.dll" ".\XEngine_Bin\XEngine_AVHelp.dll"
copy /y "..\libxengine\XEngine_Windows\x86\XEngine_AVCoder\XEngine_AVPacket.dll" ".\XEngine_Bin\XEngine_AVPacket.dll"

copy /y "..\libxengine\XEngine_Windows\x86\XEngine_LibEx\AVCodec\avcodec-58.dll" ".\XEngine_Bin\avcodec-58.dll"
copy /y "..\libxengine\XEngine_Windows\x86\XEngine_LibEx\AVCodec\avdevice-58.dll" ".\XEngine_Bin\avdevice-58.dll"
copy /y "..\libxengine\XEngine_Windows\x86\XEngine_LibEx\AVCodec\avfilter-7.dll" ".\XEngine_Bin\avfilter-7.dll"
copy /y "..\libxengine\XEngine_Windows\x86\XEngine_LibEx\AVCodec\avformat-58.dll" ".\XEngine_Bin\avformat-58.dll"
copy /y "..\libxengine\XEngine_Windows\x86\XEngine_LibEx\AVCodec\avresample-4.dll" ".\XEngine_Bin\avresample-4.dll"
copy /y "..\libxengine\XEngine_Windows\x86\XEngine_LibEx\AVCodec\avutil-56.dll" ".\XEngine_Bin\avutil-56.dll"
copy /y "..\libxengine\XEngine_Windows\x86\XEngine_LibEx\AVCodec\postproc-55.dll" ".\XEngine_Bin\postproc-55.dll"
copy /y "..\libxengine\XEngine_Windows\x86\XEngine_LibEx\AVCodec\swresample-3.dll" ".\XEngine_Bin\swresample-3.dll"
copy /y "..\libxengine\XEngine_Windows\x86\XEngine_LibEx\AVCodec\swscale-5.dll" ".\XEngine_Bin\swscale-5.dll"