copy /y "..\libxengine\XEngine_Windows\x86\XEngine_BaseLib\XEngine_BaseLib.dll" ".\XEngine_Bin\XEngine_BaseLib.dll"
copy /y "..\libxengine\XEngine_Windows\x86\XEngine_AVCoder\XEngine_VideoCoder.dll" ".\XEngine_Bin\XEngine_VideoCoder.dll"
copy /y "..\libxengine\XEngine_Windows\x86\XEngine_AVCoder\XEngine_AudioCoder.dll" ".\XEngine_Bin\XEngine_AudioCoder.dll"
copy /y "..\libxengine\XEngine_Windows\x86\XEngine_AVCoder\XEngine_AVCollect.dll" ".\XEngine_Bin\XEngine_AVCollect.dll"
copy /y "..\libxengine\XEngine_Windows\x86\XEngine_AVCoder\XEngine_AVHelp.dll" ".\XEngine_Bin\XEngine_AVHelp.dll"
copy /y "..\libxengine\XEngine_Windows\x86\XEngine_AVCoder\XEngine_AVPacket.dll" ".\XEngine_Bin\XEngine_AVPacket.dll"

copy /y "..\libxengine\XEngine_Windows\x86\XEngine_BaseLib\XEngine_BaseLib.lib" ".\XEngine_Lib\XEngine_BaseLib.lib"
copy /y "..\libxengine\XEngine_Windows\x86\XEngine_AVCoder\XEngine_VideoCoder.lib" ".\XEngine_Lib\XEngine_VideoCoder.lib"
copy /y "..\libxengine\XEngine_Windows\x86\XEngine_AVCoder\XEngine_AudioCoder.lib" ".\XEngine_Lib\XEngine_AudioCoder.lib"
copy /y "..\libxengine\XEngine_Windows\x86\XEngine_AVCoder\XEngine_AVCollect.lib" ".\XEngine_Lib\XEngine_AVCollect.lib"
copy /y "..\libxengine\XEngine_Windows\x86\XEngine_AVCoder\XEngine_AVHelp.lib" ".\XEngine_Lib\XEngine_AVHelp.lib"
copy /y "..\libxengine\XEngine_Windows\x86\XEngine_AVCoder\XEngine_AVPacket.lib" ".\XEngine_Lib\XEngine_AVPacket.lib"

copy /y "..\libxengine\XEngine_Include\XEngine_CommHdr.h" ".\XEngine_Include\XEngine_CommHdr.h"
copy /y "..\libxengine\XEngine_Include\XEngine_BaseLib\BaseLib_Define.h" ".\XEngine_Include\BaseLib_Define.h"
copy /y "..\libxengine\XEngine_Include\XEngine_BaseLib\BaseLib_Error.h" ".\XEngine_Include\BaseLib_Error.h"
copy /y "..\libxengine\XEngine_Include\XEngine_AVCoder\VideoCoder_Define.h" ".\XEngine_Include\VideoCoder_Define.h"
copy /y "..\libxengine\XEngine_Include\XEngine_AVCoder\VideoCoder_Error.h" ".\XEngine_Include\VideoCoder_Error.h"
copy /y "..\libxengine\XEngine_Include\XEngine_AVCoder\AudioCoder_Define.h" ".\XEngine_Include\AudioCoder_Define.h"
copy /y "..\libxengine\XEngine_Include\XEngine_AVCoder\AudioCoder_Error.h" ".\XEngine_Include\AudioCoder_Error.h"
copy /y "..\libxengine\XEngine_Include\XEngine_AVCoder\AVCollect_Define.h" ".\XEngine_Include\AVCollect_Define.h"
copy /y "..\libxengine\XEngine_Include\XEngine_AVCoder\AVCollect_Error.h" ".\XEngine_Include\AVCollect_Error.h"
copy /y "..\libxengine\XEngine_Include\XEngine_AVCoder\AVHelp_Define.h" ".\XEngine_Include\AVHelp_Define.h"
copy /y "..\libxengine\XEngine_Include\XEngine_AVCoder\AVHelp_Error.h" ".\XEngine_Include\AVHelp_Error.h"
copy /y "..\libxengine\XEngine_Include\XEngine_AVCoder\AVPacket_Define.h" ".\XEngine_Include\AVPacket_Define.h"
copy /y "..\libxengine\XEngine_Include\XEngine_AVCoder\AVPacket_Error.h" ".\XEngine_Include\AVPacket_Error.h"